### ISSUE TITLE
server keeps force closing and we don't know why

### ISSUE THREAD

**Issue by vicphoenix12** [AMPZNetwork/Hexx-Rewritten-4#2]
we've been playing the game for the last few days now and now we're getting this every time we load into it a few minutes afterwards if force closes the server we don't know why 
[crash-2020-09-22_16.42.54-server.txt](https://github.com/AMPZNetwork/Hexx-Rewritten-4/files/5264183/crash-2020-09-22_16.42.54-server.txt)
[crash-2020-09-22_17.06.47-server.txt](https://github.com/AMPZNetwork/Hexx-Rewritten-4/files/5264299/crash-2020-09-22_17.06.47-server.txt)

**Comment by LabsZero** [comment]
From what i can tell the issue something to do with world ticks I suggest you delete the server.propities file and regenerate it. 

if that dose not help please open a new support issue.
